### ISSUE TITLE
Yii requirement checker

### ISSUE THREAD

**Issue by pli888** [yuzebo/yii-blog#1]
> I don't know what picture about check the Yii installation in your web server using the requirement checker application.

In the Installing Yii section on the [Testdriving with Yii](http://www.yiiframework.com/doc/blog/1.1/en/start.testdrive) webpage, there is this text:

> After installing Yii, open a browser window and access the URL http://www.example.com/yii/requirements/index.php. It shows the requirement checker provided in the Yii release. For our blog application, besides the minimal requirements needed by Yii, we also need to enable both the pdo and pdo_sqlite PHP extensions so that we can access SQLite databases.

@yuzebo Maybe you can try [http://127.0.0.1/yii/requirements/index.php](http://127.0.0.1/yii/requirements/index.php) as a quick test to see if the requirement checker is working?

**Comment by yuzebo** [comment]
Complete.

**Comment by pli888** [comment]
Please describe what you did to complete this issue. Also, insert a screenshot to show the requirement checker here.

**Comment by yuzebo** [comment]
![Requirement checker](https://github.com/yuzebo/yii-blog/blob/develop/screenshot/requirement.png) This is the screenshot.

**Comment by pli888** [comment]
Ok, if you are using Postgresql as your database system for your blog application then the requirements checker application shows that Yii has this dependency installed.
